spring:
  application:
    name: orderService

  datasource:
    url: jdbc:mysql://localhost:3306/OrderService  # URL c?a c? s? d? li?u
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083